version: "3.9"

services:
  server:
    build:
      context: ./server
    container_name: theater-server
    ports:
      - "3001:3001"
    restart: unless-stopped

  webapp:
    build:
      context: ./webapp
    container_name: theater-webapp
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SOCKET_URL=http://localhost:3001
    restart: unless-stopped
    depends_on:
      - server
